name: Build
description: Builds xtgeoapp-grd3dmaps

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install xtgeoapp-grd3maps
      run: |
        python -m pip install -U pip
        pip install .
      shell: bash

    - name: List all installed packages
      run: pip freeze
      shell: bash
