name: Build
description: builds xtgeoapp-grd3dmaps

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      run: python -m pip install "pip<22.0.4"
      shell: bash

    - name: install xtgeoapp-grd3maps
      run: pip install .
      shell: bash
