name: Test vs ERT

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_vs_ert:
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: "./.github/actions/test_setup"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test vs ERT
        # the promise install is needed due to bug in ERT installer; remove when fixed
        run: >
          python -m pip install ert>=2.38.0b5 &&
          python -m pip install promise &&
          python -m pytest tests/test_vs_ert --disable-warnings -x
