name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: "./.github/actions/test_setup"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test
        run: python -m pytest tests/test_scripts --disable-warnings -x
